name: Nix-Git

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Cachix
        uses: cachix/cachix-action@v16
        with:
          name: walker-git
          authToken: '${{ secrets.CACHIX_GIT_AUTH_TOKEN }}'

      - name: Build default package
        run: nix build -L --extra-substituters "https://walker-git.cachix.org" .#default --print-out-paths | cachix push walker-git